import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const epilogue = localFont({
  src: [
    {
      path: "./fonts/epilogue/Epilogue-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/epilogue/Epilogue-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/epilogue/Epilogue-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/epilogue/Epilogue-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/epilogue/Epilogue-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-epilogue",
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${epilogue.variable} antialiased`}>{children}</body>
    </html>
  );
}
