import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import TopHeader from "@/app/components/layout/TopHeader";
import Header from "@/app/components/layout/Header";
import Categories from "@/app/components/layout/Categories";

const epilogue = localFont({
  src: [
    {
      path: "./fonts/epilogue/Epilogue-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/epilogue/Epilogue-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/epilogue/Epilogue-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/epilogue/Epilogue-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/epilogue/Epilogue-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-epilogue",
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${epilogue.variable} antialiased`}>
        <div className="max-w-[1920px] w-full mx-auto pb-[16px]">
          <TopHeader />
          <Header />
          <Categories />
        </div>
        <div className="bg-grey_200 max-w-[1920px] px-[240px]">{children}</div>
      </body>
    </html>
  );
}
